//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWideWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelloWideWorldTable
    {
        public long id { get; set; }
        public string Text { get; set; }
    }
}
